### ISSUE TITLE
No issue but an add on for the minimig wiki page.

### ISSUE THREAD

**Issue by rrmagro** [MiSTer-devel/Minimig-AGA_MiSTer#1]
Hello, this is not an "imposition" but you said that to get the roms you could get them from the original hardware or buy an Amiga Forever product, from their site.

Please consider this in the google play store.
https://play.google.com/store/apps/details?id=com.cloanto.amigaforever.essentials

I think if you just whant to test this core this is a cheaper alternative, you could add this in the wiki.
And it's still legal, since you have bought them.

Regards,
Rui Magro.

**Comment by sorgelig** [comment]
so it's a set of plain ROMs? did you test it by yourself?

**Comment by rrmagro** [comment]
No I didn't test it my self y just saw it in a YouTube video related to emulating the amiga, the guy said that could be an alternative to buying the the cds from cloanto but I'll take a look at their webpage.

**Comment by rrmagro** [comment]
Here's two links from their page.
https://www.amigaforever.com/news-events/af-essentials-android/
https://www.amigaforever.com/android/
