### ISSUE TITLE
pressing F11 to run hrtmon causes guru: 8000 000b

### ISSUE THREAD

**Issue by apolkosnik** [MiSTer-devel/Minimig-AGA_MiSTer#10]
I've tried the latest update, and 56MB RAM is not working causing bootloop with KS3.1.
Additionally, when I was trying to get to hrtmon on 020 config, it would just give me a guru.

**Comment by nretro** [comment]
You need a 64MB ram module for the 56MB fast ram feature. Chances are, that yours is still the standard 32MB one, which would also pretty much fit your description. 24MB should be sufficient for most Amiga applications. But you can of course get a 64MB module once they are available.

**Comment by apolkosnik** [comment]
I've got the 256MB module that tested ok at 167MHz.

**Comment by sorgelig** [comment]
256MB i bet is 256Mbit which is 32MB.

**Comment by apolkosnik** [comment]
AS4C16M16SA-6TCN is the chip... Yeah, you are absolutely right, the eBay seller made it look like it was 256MB, and sold me 32MB. I was trying to avoid 256mbit, but fell for this. Oh well, let's see what eBay will say.

**Comment by sorgelig** [comment]
yes, it's 32MB.
Some sellers write 256MB to make users think their module has more memory. Cheap commercial tricks.

**Comment by apolkosnik** [comment]
Thanks for clearing out the memory piece for me.

Pressing F11 is still causing the guru meditation.

**Comment by nretro** [comment]
You need to use this binary, unzip it, name it HRTMON.ROM  and put it either in /media/fat or /media/fat/Amiga.

https://github.com/nretro/Minimig-AGA_MiSTer/blob/MiSTer/releases/hrtmonV2.37WinUAE.zip

**Comment by apolkosnik** [comment]
Thanks @nretro, it works now.
