### ISSUE TITLE
fire button not working

### ISSUE THREAD

**Issue by lewelby** [MiSTer-devel/Minimig-AGA_MiSTer#108]
if you set all the minimig buttons from right to pause, then the fire button stop working and you will not be able to start any game.
To workaround this issue i have to clear all the minimig button binding  and then stop the button biding step after B.

**Comment by sorgelig** [comment]
I have all buttons defined and they are all working.
Make sure CD32 Pad option is OFF - not every game support this mode.
Also try other gamepad to make sure it's not s gamepad specific issue.

**Comment by lewelby** [comment]
i had the cd32 Pad option ON.
everything works fine now.
thanks
