### ISSUE TITLE
Won't boot from Hard Drive after update to Minimig_20210630.rbf

### ISSUE THREAD

**Issue by zompiexx** [MiSTer-devel/Minimig-AGA_MiSTer#115]
Hi. I am unable to boot from Hard Drive image after upgrading core to Minimig_20210630.rbf. I can still boot from floppy.

**Comment by sorgelig** [comment]
already discussed here:
https://misterfpga.org/viewtopic.php?f=4&t=2863

Your HDD image is not full.

**Comment by lencio** [comment]
Same here, all my hdf files not work now. It’s not possible to fix it?.
Thanks!

**Comment by sorgelig** [comment]
I've already pushed updates to support headerless HDF.

**Comment by lencio** [comment]
> I've already pushed updates to support headerless HDF.

I cant load hdf files with latest version.
In version 21.03.05 I can load all my hdf files without problems.
One example: https://mega.nz/#!aMlWgKJT!ng3YpI3F9xnXQXHxDDDOiHvl5CfgMa5jt9PexEE11Ok
