### ISSUE TITLE
HDF can't be loaded since last update

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/Minimig-AGA_MiSTer#117]
I've already pushed updates to support headerless HDF.

_Originally posted by @sorgelig in https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/issues/115#issuecomment-874333164_

I cant load hdf files with latest version.
In version 21.03.05 I can load all my hdf files without problems.
One example: https://mega.nz/#!aMlWgKJT!ng3YpI3F9xnXQXHxDDDOiHvl5CfgMa5jt9PexEE11Ok

**Comment by ch570512** [comment]
Similar problem here: Since Release 20210630 it does not find the Pri. Slave HDD.
Back to Minimig_20210305 it works again even with the newes MiSTer.

**Comment by sorgelig** [comment]
i see problem with slave disk access.
However if disk posted above is primary master then no problem to boot from it on latest release.
Make sure you've updated Main as IDE code is inside Main, not in core!

**Comment by lencio** [comment]
> i see problem with slave disk access.
> However if disk posted above is primary master then no problem to boot from it on latest release.
> Make sure you've updated Main as IDE code is inside Main, not in core!

The problem is in master disk too. I can't boot with latest Main and latest Miminig.
The disk in my link is a boot disk.

**Comment by sorgelig** [comment]
try this build:
[MiSTer.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/6768791/MiSTer.zip)

**Comment by ch570512** [comment]
Nope.
Pri. Slave not found in Minimig_20210705.rbf
but works fine in Minimig_20210305.rbf

(But boots all the time from Pri. Master - at least at my place)

**Comment by lencio** [comment]
> try this build:
> [MiSTer.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/6768791/MiSTer.zip)

Works!, what version is that Main core? the same with updateLall?
I tested with latest Main from update_all again and not work.
Only works with version that you supplied in this thread.
With your main supplied (Mister.zip), Mouse not work in minimig.

**Comment by sorgelig** [comment]
It's test build. you can download it only here for now.

this build has further fixes:
[MiSTer.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/6771398/MiSTer.zip)

**Comment by lencio** [comment]
> It's test build. you can download it only here for now.
> 
> this build has further fixes:
> [MiSTer.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/6771398/MiSTer.zip)

I'm trying with this build, and hdf and mouse works again. If I find more errors, will report you.
When you have planned to release this version?
Thanks Alexey.

**Comment by sorgelig** [comment]
should be fixed and released already
