### ISSUE TITLE
Creeping Me Out (Scorpion) crash with Fast IDE

### ISSUE THREAD

**Issue by bidinou** [MiSTer-devel/Minimig-AGA_MiSTer#118]
Hi ! I've noticed that this new upcoming Scorpion game crashed systematically with the new recent Minimig core changes. It probably applies to other Scorpion engine games.

Demo available here : http://mixelslab.com/cmo-hex-night-amiga/  ("second release").

First, note there are 2 executables : the regular one and an uncompressed one.
The regular one crashes in all cases (GURU 8100 0005). 

Regarding the uncompressed version :

- With the Minimig core prior to the recent changes (fast IDE, updated 68000 & 68020 etc.) the game just works.
- With the new Minimig core :
    - If Fast IDE is enabled, I get the aforementioned GURU (and I can see "could not deplode data/0.gfx" in the terminal)
    - If Fast IDE is disabled, the game works

Tests performed with no startup sequence as indicated in the readme.

**Comment by bidinou** [comment]
Oh my... I really thought my results were reproducible but I tried again and now constantly get the GURU with the new core even when Fast IDE is disabled.

So it must be something else which changed in the past 2 updates.

**Comment by sorgelig** [comment]
try this build of Main.
[MiSTer.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/6771318/MiSTer.zip)
If you copied/extracted the game on MiSTer then do it again from freshly downloaded game archive.

**Comment by bidinou** [comment]
Hey Sorge, this new version fixes the issue ! Both executables now work with the new core :)
Thank you so much ! :)
