### ISSUE TITLE
"Pri. Slave HDD" is not recognized

### ISSUE THREAD

**Issue by ch570512** [MiSTer-devel/Minimig-AGA_MiSTer#119]
I'm using 2 HDD on "Primary". One to boot from and one for data.
Since Release 20210630 the "Pri. Slave HDD" is not recognized anymore.
I get the error message "Please insert volume in any drive" in Amiga OS.
Reverting back to Minimig_20210305 it works fine again even with the latest Main.

**Comment by sorgelig** [comment]
i need to look at that slave image

**Comment by ch570512** [comment]
Hi sorgelig

It's bit strange. I played around with HDToolBox and now the problem is gone.
It may have been a problem in my configuration of Amiga OS 3.1 raising with the new release.

Best regards
Thorsten
