### ISSUE TITLE
Can't load Kickstart from subdir

### ISSUE THREAD

**Issue by tvierling** [MiSTer-devel/Minimig-AGA_MiSTer#12]
Most cores allow loading system ROM images from any directory, defaulting to the core's subdir ("Minimig" in this case). This core is requiring that they be in the root directory only.

Don't know how difficult this is to implement, but it would be a nice decluttering of the root directory since I switch between multiple Kickstart versions.

**Comment by nretro** [comment]
I have all my ROMs in a zip file named /media/fat/Amiga/Kickstarts.zip. Default directories are root and root/Amiga, but it is definitely possible to load it from most directories. Haven't checked if there are some exceptions.

**Comment by tvierling** [comment]
Ah, that's different from most cores, which use their basename as the default subdir (which in this case is implied to be "Minimig" rather than "Amiga"). The file selector for Kickstart doesn't provide directory up/down navigation like other file selectors, so I wasn't able to go into "Minimig" to select something.

Definitely worth adding to the top level README.md: default file selector subdir is "Amiga".

**Comment by nretro** [comment]
OK, right... it has to go into the "Amiga" directory. I completely forgot that. The Wiki is out of date. There are many things we should add.That's on my todo list for winter.
