### ISSUE TITLE
More Chip RAM (up to 8 MB as in emulators)

### ISSUE THREAD

**Issue by Andiweli** [MiSTer-devel/Minimig-AGA_MiSTer#125]
Hello!

What about additional Chip RAM up to 8 MB as some emulators offer too.
I mean not for gaming or so, more for Workbench use.

Thanks

**Comment by sorgelig** [comment]
That's not straight forward if i remember right. 8MB won't appear magically in WB without patches.
MiSTer provides RTG for WB - this is what you really need. It doesn't depend on amount of ChipRAM and much faster.
