### ISSUE TITLE
No Minimig boot animation

### ISSUE THREAD

**Issue by Andiweli** [MiSTer-devel/Minimig-AGA_MiSTer#129]
Sorry this silly question, but I googled and didn't find anything.
All I did was copying...

- minimig.art
- minimig.bal
- minimig.cop

...to the root of the MiSTer SD and set...

- bootscreen=1

But I never see the nice animation.

**Comment by sorgelig** [comment]
You need to place these files to games/Amiga (where your hard disks and floppies are).
Note: animation is shown only once when core is loaded. Minimig reset doesn't show animation.

**Comment by Andiweli** [comment]
Oh thanks! I always used the root dir.
