### ISSUE TITLE
Game Jim Power crashing 

### ISSUE THREAD

**Issue by foxp4v** [MiSTer-devel/Minimig-AGA_MiSTer#13]
Hello, i've tested all the available Jim Power in Mutant Planet ADFs and the only ones that works are the AGA patched One and the Whdload version that is probably AGA patched too. The standard ones crashes when the games has to start, sometimes does not crash immediatly but it gives the "Game Over" screen without having played and then it crash.

**Comment by apolkosnik** [comment]
I think this is fixed already.

**Comment by sorgelig** [comment]
This game works fine in latest release in 68000 mode.
