### ISSUE TITLE
Blank+ messes up the graphics in e.g. Twintris

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Minimig-AGA_MiSTer#132]
Perhaps it can be avoided that Blank+ messes up the graphics in some games?

Please check this video:
https://www.dropbox.com/s/gfdbriscmjuy37e/2021-09-07%2001.47.41.mp4?dl=0

**Comment by sorgelig** [comment]
Blank+ is optional feature. It won't work in 100% cases as it's hack.

**Comment by dfilskov** [comment]
How then would you make the core display the entire screen with normal Blank setting? - note that the side borders - left and right - are missing / cropped when using just Blank:

![Screenshot_20210908-162431~2](https://user-images.githubusercontent.com/15096058/132528373-d4afaf1d-565f-4799-900f-11b3dbec49c3.png)

... when they should look like this (this screenshot is not from MiSTer):
![Screenshot_20210908-162513~3](https://user-images.githubusercontent.com/15096058/132528467-378d9e91-9130-4bc8-a86c-721ffc9a303e.png)

**Comment by sorgelig** [comment]
Amiga has no real blank signals. It's up to specific game/app how much blank signal to leave. That's why there is a manual video adjustment for Minimig core.
I've implemented Blank+ as a way to guess the maximum used size of video. It not always works correctly due to many ways to output graphics. 
If normal blank option works, then it's not an issue.

**Comment by dfilskov** [comment]
That makes sense - thanks!

However normal blank doesn't work.

Blank+ makes the game graphics total gibberish as in the video.

Blank crops the side-borders as shown above in the two images (the last one is from a real Amiga I think and the first cropped one is from MiSTer with normal Blank (not Blank+ ... that would be "garbage").

**Comment by sorgelig** [comment]
Choose "Adjust screen position" and while adjusting press backspace button to reset setting. Does it help?

**Comment by dfilskov** [comment]
Yes! - but the issue comes back when I press Finish screen adjustment.

**Comment by sorgelig** [comment]
after backspace you can press enter to accept new settings. Anyway, it's specific adjustment you made for other game which uses the same resolution but different blank area.

**Comment by dfilskov** [comment]
Thanks - it seems tapping Enter and clicking 'Finish screen adjustment' do the same thing - for some reason both actions forget / erase the correct screen adjustment - and the graphics are cropped at the side borders again.

Please see the result here:
https://www.dropbox.com/s/2mdisor74vqpnwf/2021-09-10%2008.56.06.mp4?dl=0

**Comment by sorgelig** [comment]
something weird is happened i think. You may delete /config/minimig_vadjust.dat file (and restart Minimig core) which will erase all video adjustments in minimig.

**Comment by dfilskov** [comment]
Same ting happened - the image looks perfect but when I press Enter the issue / cropped borders come back. Even when I delete the minimig_vadjust.dat first.

The minimig_vadjust.dat re-appears - attached.

[minimig_vadjust.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/7145957/minimig_vadjust.zip)

Perhaps it's an untested result of the quite new HV-Integer feature and Blank+ combined?

**Comment by sorgelig** [comment]
Are you still using Blank+? Don't use it (at least with this game)

**Comment by dfilskov** [comment]
I'm not using Blank+ no - otherwise I can't even see the graphics at all :)

I meant that since the Blank+ exists it might affect the screen adjustment even though it's turned off.

The missing borders could also simply be an unrelated old issue with the screen adjustment feature. Let me know if I should test something else to get further info on why it doesn't save correctly.

**Comment by sorgelig** [comment]
I've tried this game (WHDLoad) and didn't find such issue. A whole screen is visible and i'm able to adjust the video as i like.
So i don't know what's wrong on your setup.
