### ISSUE TITLE
Screen adjustment isn't saved

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Minimig-AGA_MiSTer#133]
When you adjust / reset the screen (by tapping Backspace) and press Enter (or F12 and then 'Finish screen adjustment') the adjustment is reset.

Please see this video for repro'ing:
https://www.dropbox.com/s/3wazbzv24d3raof/2021-09-12%2019.45.06.mp4?dl=0

Not sure if this affects it but my HDMI framerate is ~60 Hz.

**Comment by sorgelig** [comment]
you doing it wrong.
The file you deleted is already loaded into memory. 
As i've told you in other issue, you have to RELOAD the core. Better to reboot the MiSTer after file deletion.

**Comment by dfilskov** [comment]
Oh - sorry - yes, missed that. I did what you wrote now but didn't change the behavior. Deleted the file and even rebooted MiSTer entirely.

Now I've deleted all the (nine) minimig files in config (there were som map files too), allowed for 50 Hz in the MiSTer.ini (and set video_mode=8) and now use another screen running 1920x1080 to make sure I'm matching the typical setup - perhaps it resembles yours too ... will let you know.

**Comment by dfilskov** [comment]
Thanks for yor help so far!

It's very weird ... it worked for a while. I got the red screen with the yellow hammer and sickle to work and Store the adjustment correctly showing the full image. Also the Twintris selection menu looked good.

But then after proceeding into the actual game (the two Tetris views side by side) and adjusting the screen there storing the adjustment reset it to the wrong cropped view once again.

Now I can't make it go back to the correct view again even if I delete all minimig files in config and turn MiSTer off - it just crops as soon as I tap Enter like before. If I leave it after tapping Backspace it shows the screen perfectly until I tak Enter or Esc.

It did save the minimig_vadjust.dat again but it had the exact same content as the 'correct one' even though this time it didn't work. Later the content changed again when I tried to repro.

This makes me wonder if the adjustment for each resolution isn't only stored inside the minimig_vadjust.dat but perhaps somewhere else when it's the same file but the output is different. I've attached the minimig_vadjust.dat file that worked but suddenly stopped working even with the same content.

Perhaps you could try minimig_vadjust.dat file and/or try to proceed into the actual Twintris game and adjust the screen there again too - and in the Menu once again - and see if you get the pefect result contrary to me. Meanwhile I'll see if I can repro this sporadic / unpredictable behavoir and find out more about what causes / provokes it.

[minimig_vadjust.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/7150337/minimig_vadjust.zip)

**Comment by dfilskov** [comment]
I've now tested most releases back to Minimig_20191007.rbf - the issue was still there. I can't test releases earlier that than on my updated MiSTer.

**Comment by dfilskov** [comment]
A work-around is to simply let Minimig stay in "Screen adjustment mode" while playing - that would be a great option too in the menu: "Reset and store adjustment" . At least in a test build perhaps.

Please let me know if there's anything else I could test that could help us find out what's causing this.

**Comment by sorgelig** [comment]
I cannot reproduce your issue unfortunately... I've used your file and on first loading i got same missing left and right parts of video. Then i've adjusted the video using "Adjust screen position" and pressed enter. It's correctly remembered. I have correct video now. 
No resets of position as you described.

**Comment by sorgelig** [comment]
Did you remap keyboard buttons somehow? May be your "enter" somehow acts as "ESC" key?
Try other keyboard to make sure.

**Comment by dfilskov** [comment]
I'll try - thanks! - but the issue is also present when I press the OSD button and then 'Finish screen adjustment' in the menu. That should be certain to do the right thing but it doesn't.

Nevertheless I'll test with another keyboard.

**Comment by sorgelig** [comment]
May be try this: 
take a new SD card and make fresh MiSTer install there with as less customization as possible, without ini file. Add there Minimig HDD files. Then try.

**Comment by dfilskov** [comment]
That worked - a fresh / clean SD card. So we're getting closer.
Afterwards I tried running my current SD card without the MiSTer.ini - that didn't work.
Then I tried copying the Minimig config files from the clean SD card to my current SD card - still without the MiSTer.ini file - that didn't work either.
Then I cleaned my current SD card (using the SD card installer) so that it was 'fresh' and copied all my files from my current SD card (except from the linux folder, MiSTer, MiSTer.ini and menu.rbf ) - that didn't work either.

**Comment by dfilskov** [comment]
Now I tried my current MiSTer.ini on a clean SD card. That worked so it's not my ini settings.

**Comment by dfilskov** [comment]
Now I tried copying
minimig.cfg
Minimig_volume.cfg
minimig_vadjust.dat
... from the clean working SD card to my current SD card. That didn't work either.

Hmm not sure what to try next ...

**Comment by sorgelig** [comment]
May be ask on forum to check how many ppl have this issue

**Comment by dfilskov** [comment]
Hey I've made progress ... it has something to do with which files are in the games/Amiga folder. When I removed all files in the Amiga folder and added only the necessary ones it worked! - so now I'm trying to find out which file inside the Amiga folder that ruins the screen adjustment setting.

**Comment by dfilskov** [comment]
GOT IT!

For some reason - inside the 'shared' folder (in games/Amiga) there was a minimig_vadjust.dat ... not sure how it ended up there but deleting it made it all work again :)

So is that a bug somehow? - I thought the 'shared' folder was for mounting a drive inside Workbench - not something the core would use for config files.

**Comment by sorgelig** [comment]
Ok. i remember there was a request to search minimig_vadjust in shared folder first. It's for cases when inside Amiga there is a script/app which will modify this file before launching specific game. So it's made to be able to have it per-game adjustments.

So just delete this file from shared folder if you don't use such feature.

**Comment by dfilskov** [comment]
Makes sense! - perhaps when the user starts the screen adjustment a pop-up could say "Using minimig_vadjust.dat in shared" if such a file exists.
