### ISSUE TITLE
MiSTer Monitor displays garbage above 1280x720

### ISSUE THREAD

**Issue by Andiweli** [MiSTer-devel/Minimig-AGA_MiSTer#134]
Hi there!

Perhaps someone can help...

My monitor is an ASUS VS278H with 1920x1080 and above (scaled down).
Even my old Raspberry with UAE is capable of displaying 1920x1080 properly up to 32 bits.
But the MiSter graphics driver on AmigaOS only displays flicker and garbage on any resolution above 1280x720 :(

I already tried some other settings in Picasso-Settings, without success.
Any idea or help?

Thanks & kind regards

**Comment by sorgelig** [comment]
Please post your question on MiSTer forum as it's specific to your setup.
