### ISSUE TITLE
Add UI support to "hardwire" a Joystick Button (2, 3... N) to "JOYSTICK UP".

### ISSUE THREAD

**Issue by sromeroi** [MiSTer-devel/Minimig-AGA_MiSTer#135]
Note: This is just an UI request making something more accessible / easy to configure to users.

As you know, even if the Amiga supported 2 buttons joysticks, most of the developers targeted 1-button joysticks and used only 1 button for their games.

Example: On most platformers, button was used as FIRE while the player had to use JOYSTICK UP for jumping. Or, games like Super Off Road used JOYSTICK UP for acceleration and the button for Nitros. This means that you need to press UP the whole game for your car to move, even while turning, and this makes the game uncomfortable to play compared to console versions.

Most users modified their 2-button joysticks and connected the second button to the UP direction with a wire. After this, pressing button 2 was the equivalent to pressing UP in the joystick, and then you could Jump, or Accelerate or Whatever with Button 2.

I'm solving this right now with the "Alternate buttons" config (a second "UP" mapping to blue button) but it might be handy to have a quick option for it in the UI to easily enable/disable it, something like:

- Connect joystick button to UP: [ Off / Button 1 / Button 2 / Button 3 ... ]

It should be quite straightforward to implement but will provide a lot of vale for Amiga gamers (me included) as you can quickly enable/disable it with F12 when required, instead of having a "SAVED" keyboard mapping that you have to redefine and save each time.

Thanks :)

**Comment by sorgelig** [comment]
Alternative set is made exactly for such cases.
Alternatively you may use "Button/key remap for game" to have temporary map when you play such game.

**Comment by sromeroi** [comment]
Thanks for your quick response.

Yes, I know, that's how I'm doing it right now, but there are games supporting 2 buttons and games that not, and this implies reconfiguring the entire keyboard each time.

About "Button/key remake for game", I (as most amiga users) use a virtual disk (HDF) running the Amiga OS and then launching games within that O.S. (typically whdload games launched from iGame or TinyLauncher) ... so, is this option able to detect the game you're launching and act only on that game? :-?

I asked on a couple of telegram MiSTer and Amiga channels and several people found the option quite interesting. It is something that Amiga users will use (and change) for sure several times, in a regular basis.

**Comment by sorgelig** [comment]
> but there are games supporting 2 buttons and games that not, and this implies reconfiguring the entire keyboard each time.

you don't need it. Simply use primary map for normal games and use alternatively mapped buttons for games where it needs. Modern gamepads have many buttons to have both maps at the same time.

Core cannot detect the game inside Amiga.

**Comment by sromeroi** [comment]
It looks like you don't see this feature interesting, so, I'm just closing the issue as it looks I reached a dead end.

Thanks anyway for your time and responses.

**Comment by cheskote** [comment]
I think this feature would be useful
