### ISSUE TITLE
Image not centered in CRT and strange behavior of "Adjust Screen Position"

### ISSUE THREAD

**Issue by sromeroi** [MiSTer-devel/Minimig-AGA_MiSTer#137]
Hi.

Minimig appears off-centered in my SONY Trinitron 14". A have a vertical black bar in the left side of the screen and I lose some part of the image in the right side.

I tried the "Adjust Screen Position" option in the UI but the behavior is quite strange: instead of moving the image to the left to center it, it is "adding" more "white space" while the screen remains in the same position. And even changing that "visible space" (which does not fix the centering issue), when I press ENTER and I see the "Stored" message, nothing changes and the black bar remains the same size/position.

I've recorded a small video to illustrate the issue:

[Youtube: Adjust Screen Position minimig](https://youtu.be/eEcfhFoi1sI)

(Please note the ~2cm of "black space" at the left of the image)

Any idea on what I'm doing wrong?

**Comment by sorgelig** [comment]
Screen adjusting on Minimig is for HDMI output, not VGA.
Overall video of this core is mostly for HDMI, especially RTG.
You may use cga_scaler=1 option in INI which will give HDMI resolution over VGA output and then you will be able to adjust screen position.

**Comment by sromeroi** [comment]
Hi.

HDMI resolution means that I need to use an VGA monitor supporting high resolutions? will I be able to use it with an standard TV which is 240p?

I don't use RTG, I just want to "run" an standard A1200 like a classic one, over a CRT TV (15Khz), just like any typical Amiga user in the past.

Some arcade cores have the possibility to center X and Y position in the screen, is it possible to request this feature?

Thanks!

**Comment by sorgelig** [comment]
HDMI can output any resolution including VGA resolutions. 240p would be too low for Minimig. I suggest at least 480p.

**Comment by sromeroi** [comment]
Thanks for your answer regarding HDMI output.

So, there's no plan to include "Horizontal/Vertical CRT" centering in this core like other cores do? 
Would be very useful for CRT users.

Thanks a lot and sorry for insisting on this topic, I have 2 MiSTers and I'd prefer not to buy a different FPGA just for the Amiga because of this problem.

**Comment by sorgelig** [comment]
Amiga has no fixed resolution. Different games may use different parameters of video, so fixed position won't work wit Minimig.

**Comment by sromeroi** [comment]
You're completely right. Thanks for the comment. So, there's no solution for me on this then...

**Comment by capitaineflam25** [comment]
Having a CRT vertical/horizontal offset would be very appreciated ! 😍
