### ISSUE TITLE
68020 issue

### ISSUE THREAD

**Issue by tikikevin** [MiSTer-devel/Minimig-AGA_MiSTer#14]
So this is reproducible using WHDLoad and the game "Gods"

Gods on WHDLoad works great (perfect from what I can tell) on an ECS/68000 setup (PAL). But When I run the machine in AGA/68020 (PAL) it fails with the following error...

Exception "Line 111 Emulator" ($2C) at $9F3E0000 occured

I initially thought the problem was with the AGA mode on minimig. However, when I run ECS mode with 68020 instead of the default 68000, the ECS Amiga experienced the same issue. So it would appear that the 68020 implementation has an issue.

**Comment by piso77** [comment]
Does your adf run on a real 68020?

**Comment by tikikevin** [comment]
Yes... I have an Amiga 600 with a Furia/020@33Mhz and it works great. 

I have also confirmed that it works fine running WinUAE with ECS/020, and Amibian on my RPi running both ECS/020 and AGA/020

**Comment by apolkosnik** [comment]
Can you share where exactly it crashes? I was able to play on level 1, from floppy, without the WHDLoad.

**Comment by rsn8887** [comment]
I played the WHDLoad version in AGA/68020 (PAL) on my Mister yesterday, it didn't crash.

**Comment by sorgelig** [comment]
I see no issues. I think recent CPU fixes also fixed this game.
