### ISSUE TITLE
Minimig Screen Modes Strange Behaviour

### ISSUE THREAD

**Issue by ingloriond** [MiSTer-devel/Minimig-AGA_MiSTer#151]
First thank you for your excellent work. I'm not sure if this is core failure or what exactly the original Amiga would do. I normally use the mister connected to a crt 31 khz monitor, so in my mister.ini I use forced_scandoubler=1. I have noticed that in some graphic modes the core throws me the signal at 15 khz, when it shouldn't because the scandoubler is forced. When I use lcd it works fine. If I use lcd + vga it only fails in crt.  I make a thread at mister fpga forum too ( https://misterfpga.org/viewtopic.php?t=5266) if anyone could help me... no luck yet 
Link to an example link :

https://sendvid.com/dfxhn0x9

Thanks in advance

**Comment by sorgelig** [comment]
currently interlace mode isn't compatible with scandoubler

**Comment by ingloriond** [comment]
Thanks for responding so quickly.. maybe for later I guess ;)
