### ISSUE TITLE
Graphics corruption, Software failure error

### ISSUE THREAD

**Issue by Brewskii2117** [MiSTer-devel/Minimig-AGA_MiSTer#16]
Minimig_20190912 doesn't run correctly on my mister, I've got it set up as 020, aga chipset and 3.0 kickstart rom. It may be the 3.0 kick start rom it's having issues with. Tried to boot to the kickstart screen, but it will eventually "guru" and reboot if I leave it there, won't boot from a workbench adf, or from my vhd hard file. I went back to Minimig_20190717 release and it works fine.
![71145438_10157572533158841_4438578723066740736_n](https://user-images.githubusercontent.com/55276967/64853065-9f1b3480-d5e8-11e9-8e21-3ad28b49607c.jpg)

**Comment by uigiflip** [comment]
I think there many bugs in latest , people have suggested to roll back to previous core until new fixes released in a new core soon

**Comment by Brewskii2117** [comment]
That's what I've done, looking forward to the next release :)

**Comment by nretro** [comment]
Works for me with Amiga Forever 3.1 A1200 ROMs and with 3.1.4.
Since the frequency of the new release is higher, it will probably use more power. If your PSU is too weak or your cable is too long, MiSTer could be unstable for that reason. I had this problem a while ago.

**Comment by sorgelig** [comment]
I think it's simply metastability issue when one de10-nano will work ok, while other will be glitchy.

**Comment by sorgelig** [comment]
[Minimig.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/3613588/Minimig.zip)
Test version with fixes. Also has tweaks for 64MB module. 
You need to update MiSTer binary and Menu core to properly detect the SDRAM module size.

**Comment by Brewskii2117** [comment]
The test version is working great for me. Ran a few games, no issues so far. Thanks sorgelig!

**Comment by sorgelig** [comment]
This version went to release.
If it fixed your issue, then close it please.

**Comment by Brewskii2117** [comment]
Sorry, new to github. :) Thanks again.
