### ISSUE TITLE
Real-time clock not working with Kickstart 1.3

### ISSUE THREAD

**Issue by limi** [MiSTer-devel/Minimig-AGA_MiSTer#160]
(Note that I am *not* using an RTC module, just NTP since my device is connected via WiFi)

Setting the clock based on the time that MiSTer supplies seems to work on Kickstart 2.x and Kickstart 3.x. However, it fails with Kickstart 1.3.

Steps to reproduce:

1. Configure an Amiga 500-equivalent in the Minimig core (68000 processor, Kickstart 1.3).
2. Boot Workbench 1.3.4 (I believe this includes the Y2K fix that was in SetClock 34.3, but do double check the version).
3. Open the Workbench disk, then open AmigaShell.
4. Run `setclock`

What happens:
* Fails with this error message:

```1> setclock
Battery Backed up Clock not found
```

What I expect to happen:
* The time is updated to current time as supplied by MiSTer, just like it does on Workbench 2.x and 3.x setups. 

(Context: The Amiga 500 *did* ship without a battery-backed clock, but 99% of the very common 512KB memory expansions included a battery-powered clock, so this was a common thing to do in your `s:startup-sequence`)

**Comment by limi** [comment]
Also, I believe the Kickstart 2.0 and 3.0 versions do not require an explicit command to retrieve the clock from RTC, that’s only necessary on Kickstart 1.3. The time is correct on 2.0 and 3.0 systems by default.

**Comment by sorgelig** [comment]
If you will tell what registers need to be implemented, then i will make it.

**Comment by nretro** [comment]
SetClock uses a straight forward way to detect the clock. It reads the second register, waits for 1.5 seconds and than reads the seconds register again. If there is no change, there is no clock. 
This does not work with MiSTer, since RTC only gets an update every minute or so. The way to go would be to  increment the RTC registers on the FPGA side in between the updates from the HPS side.

**Comment by sorgelig** [comment]
i see. i will check it.

**Comment by sorgelig** [comment]
try this build:
[Minimig.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/10746120/Minimig.zip)

**Comment by nretro** [comment]
That works perfectly. Thanks!

**Comment by limi** [comment]
Thank you!

**Comment by limi** [comment]
Verified as working in the currently shipping core.
