### ISSUE TITLE
MT32 Support in minimig settings

### ISSUE THREAD

**Issue by ransom1122** [MiSTer-devel/Minimig-AGA_MiSTer#162]
Is there any chance we could have support for mt32 that can be enabled in core settings? 

The latest beta version of winuae now supports mt32 without any third party installed software. You drop the mt32 rom files in the directory and games work when you enable mt32 sound...

I was hoping this could be possible with thr minimig core...

**Comment by sorgelig** [comment]
Minimig already supports MT32 either through emulation on linux side or (better) through MT32-pi.

**Comment by ransom1122** [comment]
Last time I checked I thought the mt32-pi was required? You can use mt32 sound with minimig without the pi now?

**Comment by sorgelig** [comment]
Not just now. It was way before MT32-pi, but performance of de10-nano CPU is not enough for good MT32 emulation, so it may have issues.
https://github.com/MiSTer-devel/Wiki_MiSTer/wiki/USB-MIDI-with-the-Minimig-and-ao486-Cores

**Comment by ransom1122** [comment]
I see MIDI works with FSynth "Connection > MIDI / Type > FSYNTH"

Changing the Type to MUNT doesnt work..

Also none of the Soundfonts for FSynth sound nothing like MUNT MT32

I think my question should have been Support for MUNT MT32 not MIDI

**Comment by sorgelig** [comment]
Yes, MUNT is supported too. You need to choose a correct mode in OSD settings and provide a correct ROM.
But MUNT loads CPU very much and sometimes misbehave. This is why it's advised to use MT32-pi.

**Comment by ransom1122** [comment]
What location does the MT32 Roms go into?

**Comment by sorgelig** [comment]
i have these roms:
CM32L_CONTROL.ROM
CM32L_PCM.ROM
MT32_CONTROL.ROM
MT32_PCM.ROM

in `linux\mt32-rom-data` directory

**Comment by ransom1122** [comment]
I got it to work, thank you... SQ4 & PQ3 both work with MT32 Munt sounds without any problems...

**Comment by sorgelig** [comment]
Great!
