### ISSUE TITLE
Switching from pal to ntsc and vice versa makes no difference

### ISSUE THREAD

**Issue by theenemy-thd** [MiSTer-devel/Minimig-AGA_MiSTer#166]
Not sure if I am misunderstanding something or doing something wrong but when you try to change from pal to ntsc and vice versa in the osd nothing happens. Seems it is stuck in 60hz ntsc. The c64 core functions how it should and makes the screen switch 50/60hz

**Comment by sorgelig** [comment]
Because Amiga works differently. After change you need to reset Amiga and make sure BIOS picked the correct model (not forced to PAL or NTSC).

**Comment by theenemy-thd** [comment]
Thanks for clarification, I will close this now
