### ISSUE TITLE
KICK.ROM filenames?

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Minimig-AGA_MiSTer#25]
Which filenames to use if I want to switch from OCS to AGA?

KICK.ROM and which? KICK31.ROM?

**Comment by sorgelig** [comment]
Names aren't hardcoded.
So name depends on Amiga model you want to re-create.

**Comment by rsn8887** [comment]
Oh cool thanks. I thought from README.MD that it was hardcoded to "KICK.ROM"
