### ISSUE TITLE
No option to load anything from menu screen in minimig

### ISSUE THREAD

**Issue by PeteMcGann** [MiSTer-devel/Minimig-AGA_MiSTer#26]
Load latest Minimig Core, press F12 - only generic options available in menu, nothing for loading games or setting any options related to the core such as chipset, mem config. etc.

**Comment by sorgelig** [comment]
Update all MiSTer parts to latest.

**Comment by PeteMcGann** [comment]
Not sure what you mean by all Mister parts?I have updated the boot menu and the minimig core, what else should I be updating?
    On Sunday, 27 October 2019, 10:05:15 GMT, sorgelig <notifications@github.com> wrote:  
 
 
Update all MiSTer parts to latest.

**Comment by PeteMcGann** [comment]
Updated MISTer core and all works fine now, thanks.

    On Sunday, 27 October 2019, 10:05:15 GMT, sorgelig <notifications@github.com> wrote:  
 
 
Update all MiSTer parts to latest.
