### ISSUE TITLE
Caps Lock doesn't stay LOCKED when pressed

### ISSUE THREAD

**Issue by mattsoft** [MiSTer-devel/Minimig-AGA_MiSTer#3]
When pressed, the Caps Lock on USB keyboards doesn't stay locked (or unlocked), and the LED light on the keyboard does not light up.

**Comment by sorgelig** [comment]
True. I will figure out why. May be it's a feature i've forgot :)

**Comment by sorgelig** [comment]
Fixed. See https://github.com/MiSTer-devel/Main_MiSTer release.

**Comment by mattsoft** [comment]
Fix confirmed! Thanks so much!
