### ISSUE TITLE
Mouse pointer in Workbench not super smooth

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Minimig-AGA_MiSTer#30]
On my real Amiga back in the day the mousepointer in Workbench always moved buttersmooth. On Mister, the mousepointer motion is not very smooth for me. It is ok but not as much fun to control like on a real Amiga.

Is this a known problem, or should I maybe buy a new mouse? I am currently using a Logitech M185 USB mouse. On Windows, my mouse produces smooth pointer motion. In WinUAE, the mouse pointer is not as smooth as on a real Amiga, but still much smoother than in Mister. I am using a A1200 config booting into ClassicWB, but I also tried other configs.

**Comment by sorgelig** [comment]
mouse can generate a lot of communication traffic. Probably communication channel between core and Linux is saturated by mouse messages.

**Comment by rsn8887** [comment]
Maybe this could be fixed in principle by accumulating/adding all mouse movement together on Linux side and only sending the total deltas approximately once every 1/60 second or so?

**Comment by rsn8887** [comment]
Or maybe Linux already has some option to limit mouse event frequency or readout frequency. I don’t think cores need mouse messages more than once per frame.

**Comment by rsn8887** [comment]
Or maybe I can buy some different mouse  that is slower?

**Comment by rsn8887** [comment]
Also I wonder if the channel is saturated by mouse, what about six player gamepad input? Could that also saturate it already during normal/non-mouse gameplay?

For example, could Mister in principle receive delayed gamepad input when a lot is going on with multiple gamepads, due to shortcomings of communication channel? I suspect not, but it might be worth investigating.

**Comment by sorgelig** [comment]
Mouse generats hundreds more events than any gamepad or keyboard. 
Even on PC it is easy to make 100% CPU loading by quickly move the mouse. (at least some years ago).

If i remember right, Amiga mouse has quite bad principle of mouse query and get the data, so it's easy to miss the events (on Amiga software side). Probably it can be improved.

**Comment by rsn8887** [comment]
My mouse moves the pointer supersmooth in all other cores (Archie, MAC, 486, etc). Only in Amiga Workbench it is not super smooth.

**Comment by rsn8887** [comment]
I bought a different mouse ( https://www.amazon.com/gp/product/B013WC0P2A/ ) and with the new mouse now the pointer is moving as smooth as in WinUAE. In addition the new mouse has a button to adjust DPI value, which is very handy to adjust mouse sensitivity on the fly :) 

The old mouse, the one that wasn't smooth was the Logitech M185, I wouldn't recommend that one.

**Comment by sorgelig** [comment]
Amiga still uses a raw data from mouse when every tick from mouse transmitted to port. It's not like PS2 where computer reads the amount of movements since last read. So this interface still may miss the movements if core receives too large movements. So it's better to use low-DPI mouse to ensure all movements are registered and stored.
