### ISSUE TITLE
Audio channels seem inverted? Right channel is on left speaker and vice versa

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Minimig-AGA_MiSTer#34]
Tested with SWIV (WHDLoad) on A1200 config. The explosions on left side of the screen should come out of the left speaker, and vice versa. Instead they are reversed.

This had been wrong in WinUAE for a very long time, but got fixed there a couple years ago or so.

SWIV is a great game to test this with, since the sound is tied to screen position. Archon is another one.

**Comment by sorgelig** [comment]
fixed

**Comment by rsn8887** [comment]
Thank you!
