### ISSUE TITLE
Chipset OSD menu "UP" doesn't wrap around 

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Minimig-AGA_MiSTer#35]
In all core OSD menus, I can press up at the top and it wraps around to the bottom. But in minimig chipset submenu, when I go to CPU (the top option) and press up, it doesn't wrap to the bottom. If I go to the last entry in the menu, and press down, it wraps back to the top. But not the other way around.

This issue happens only in chipset menu, all other menus are fine.

**Comment by sorgelig** [comment]
fixed.

**Comment by rsn8887** [comment]
Thank you!
