### ISSUE TITLE
Overkill AGA crashes a few seconds into first level

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Minimig-AGA_MiSTer#38]
Tested both disk and WHDLoad version.

The disk version seems to work fine using the m68k test-version of this core that was posted on Atari-Forum, but that core hangs during loading when trying to load the WHDLoad version.

**Comment by sorgelig** [comment]
tg68k doesn't support all 68020 instructions yet.
m68k is still buggy.

**Comment by rsn8887** [comment]
On latest release 20191124, the game doesn’t hang or crash anymore, but gameplay mechanics are broken: The direction of spaceship movement cannot be changed correctly, spaceship position jitters, and collision detection is not correct.

**Comment by rsn8887** [comment]
Fixed in release 20191204! Thanks!
