### ISSUE TITLE
Graphical glitches over HDMI when Amiga switches between resolution modes

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Minimig-AGA_MiSTer#4]
This is most apparent when switching from an interlaced resolution mode to a non-interlaced resolution mode, and vice-versa.  From anecdotal comparisons with other MiSTer users, it sounds like this may only impact the HDMI output.

Example repro:
1) Set Workbench to use "High-Res Interlaced" mode.
2) Launch ProTracker, which opens in a non-interlaced mode.
3) Now use the z-ordering widget in the upper-right corners of Workbench and ProTracker to repeatedly switch between them.

Result: Very noticeable full-screen graphical artifacts (interleaved lines, momentary wrong-scaled image of the mode being switches away from, etc) as observed in the attached slow-motion video clips.

Expect: No graphical glitches when switching resolution modes.

[Minimig_resolution_switch_glitch_videos.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/3100927/Minimig_resolution_switch_glitch_videos.zip)

**Comment by sorgelig** [comment]
It's how Scaler works. It's not expecting dynamic resolution switch. And it's not related to Minimig.
You may reach the Scaler developer (Atari forum) and ask if it possible to fix.

Not a Minimig issue.
