### ISSUE TITLE
HRTMON not working on FX68k core

### ISSUE THREAD

**Issue by apolkosnik** [MiSTer-devel/Minimig-AGA_MiSTer#41]
Throws a delayed guru on fx68k core.

**Comment by sorgelig** [comment]
for me it works.. 
At least worked when i tried last time. 
Probably it depends on memory config.

**Comment by apolkosnik** [comment]
Ok, it looks like the patched version I got from @Retrofun is the culprit on 68000, the one from UAE works fine.
