### ISSUE TITLE
Scandoubler FX issues

### ISSUE THREAD

**Issue by apolkosnik** [MiSTer-devel/Minimig-AGA_MiSTer#42]
Set Scandoubler FX to CRT 25%, go one level up, Save Configuration. Load Configuration.
Wrapped flickering mess.

**Comment by sorgelig** [comment]
i guess you are trying interlace modes.. I think i will disable scandoubler for interlace as it's done for other cores.

**Comment by apolkosnik** [comment]
You are right, it was the interlaced screen mode. Interesting that it worked until reload.
