### ISSUE TITLE
Documentation: does Minimig implement MMU hardware?

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Minimig-AGA_MiSTer#5]
It seems that having any libraries supplied by MmuLib (found on AmiNet) installed in AmigaOS 3.1.4 causes C:SetPatch to crash with a ramlib error under Minimig, even though it works fine under WinUAE.

This isn’t caused by a lib conflict; this repros on a clean install of AmigaOS 3.1.4:

- Boots fine on Minimig without MmuLib installed.
- Fails to boot with ramlib error (happens when “C:SetPatch QUIET” is called, either during S:Startup-Sequence or when run manually) with MmuLib installed.

I've seen multiple reports in online forums from MiST and MiSTer users about this specific issue, so it's not just me.  And, this doesn't appear to repro on WinUAE or real hardware, according to the other user reports I found.

So this is apparently some kind of known incompatibility with MMU, specific to MiST and MiSTer. I’m starting to wonder if it’s because Minimig maybe just doesn’t implement the MMU coprocessor (MC68851)?  I've been unable to find any clear documentation stating whether it does or doesn't.

If MMU hardware is not implemented by Minimig, then this core's documentation should be updated to explicitly call that out.

It would also be a good idea to advise users who are hitting the ramlib error during boot to use L-MOUSE+R-MOUSE during boot to bypass S:Startup-Sequence so they can get to a command shell and remove all MMU-relevant libraries (680?0.library, mmu.library) from their Libs: folder, so that Workbench can actually boot successfully on MiSTer.  Many users are probably going to start off with MiSTer by bringing over a preexisting .hdf file they've been using just fine in some version of UAE, and they will be confused and frustrated when they see Workbench spits out a ramlib error and refuses to boot on their MiSTer.

**Comment by sorgelig** [comment]
Try to read Wikipedia if you want to know more.
MMU appeared in 68K starting from 68030.

**Comment by c0d3h4x0r** [comment]
So when a poor user tries to load their .hdf file in MiSTer -- and that .hdf file has always worked fine in UAE -- but it won't boot on MiSTer and just gives a mysterious "ramlib" error code -- how are they supposed to know that they need to go search for "mmu" and "68030" in wikipedia in order to solve their problem?

**Comment by sorgelig** [comment]
Minimig never been a clone of UAE. Not all features of UAE are available in MInimig. Set UAE to bare Amiga 1200 without any extensions (except FastRAM expansion) and most likely it will match the Minimig.
It's like to say "I've installed the Windows 95 on my i486, but then i've connected HDD to i286 PC and it doesn't boot." This is retro system. And as i've told you in FB group, users of that time were well aware what they can run.
It's specifics of retro computers. So, be prepared to read a lot in Wikipedia and specific forums to get maximum form it.
Cores provide the info which exact HW is implemented, and then it's up to the user how to intrpret it. It's already out of MiSTer's scope.
