### ISSUE TITLE
Renaming of the two old releases in the repo

### ISSUE THREAD

**Issue by kowoba** [MiSTer-devel/Minimig-AGA_MiSTer#51]
This is perhaps the daftest "OCD driven" request ever, but... could minimig_20170626.rbf and minimig_20170615.rbf be renamed to Minimig_20170626.rbf and Minimig_20170615.rbf (capital M) so that they "fall in line" with the other releases, and will not always show up at the bottom of the list on the release page along with the latest release? Thanks :)

**Comment by sorgelig** [comment]
fixed
