### ISSUE TITLE
Long blank screen delay after switching 31k (scan-doubled) screens

### ISSUE THREAD

**Issue by apolkosnik** [MiSTer-devel/Minimig-AGA_MiSTer#61]
Perhaps this is not the Minimig core bug, but at least it's easy to reproduce on this core.
I've noticed a pretty weird behavior where when you have workbench running in 31kHz screenmode (Multisync or DblPal, etc), and run something like Sysinfo, the Sysinfo screen comes up immediately, then after couple of seconds the whole screen goes blank for 20-30 seconds. This delayed long blank doesn't happen in 15kHz screen modes.

**Comment by sorgelig** [comment]
I never encountered such issue.
Actually SysInfo tries DBLPAL mode if it finds in the list of installed drivers. It means if your WB already uses DBLPAL non-interlace mode, then SysInfo won't change the video mode upon start. So i have no idea which part notices that SysInfo is started and does something with video.

Anyway, i cannot reproduce this issue even with vsync_adjust=2 mode. So, you need to investigate this problem deeper yourself to find the reason.

**Comment by apolkosnik** [comment]
Sounds good. I'm just documenting it, not expecting this weirdness to be fixed anytime soon. I've switched the display mode to PAL-hires and it's not happening.

**Comment by apolkosnik** [comment]
So, this is a problem on interlaced screens. I'm going to close this issue, since switching to non-interlaced is what makes it go away.
