### ISSUE TITLE
Out of This World/Another World Sound Glitch

### ISSUE THREAD

**Issue by xmcj** [MiSTer-devel/Minimig-AGA_MiSTer#65]
Hi all,

I am running the latest Minimig core from MiSTer Main.

When playing any version of Out of This World or Another World, during the introduction sequence, the Ferrari skidding digital sound effect is not played properly causing some crazy sounds to come out until the next scene is rendered.

I have tested both 000/020 CPU modes. I have tried turning Floppy Turbo to Off.

EDIT: I am using the official KickStart 3.1 ROM to play this game. I will also try with KickStart 1.3 and report back.

I did my best to check that this bug was not already reported nor was the product of something not implemented yet. Because this should be a digital sound effect, I am submitting my report. I will be able to provide video capture of the glitch later tonight.

**Comment by sorgelig** [comment]
i've watched the whole intro and didn't hear any oddity. Car skidding sound is fine. I'm using WHDLoad version. It's possible this game needs some special settings and WHDLoad applies them automatically.

**Comment by xmcj** [comment]
You are correct. This game seems to have issues when using a KickStart 3.1 ROM.

Switching to KickStart 1.3 solved the issue. Thank you!

**Comment by SegaSnatcher** [comment]
I'm getting some oddities with this game.   Sometimes during the intro the sound is fine and other times there are missing sound effects like when he opens up the can or hits the keypad.  It seems to be some weird timing issue.

Using Mega AGS Kickstart,
