### ISSUE TITLE
Mouse Scroll wheel is not working

### ISSUE THREAD

**Issue by apolkosnik** [MiSTer-devel/Minimig-AGA_MiSTer#66]
I ran MinimigWheelDriver (from minimig-rel2.zip at http://meditation.somuch.guru/minimig/files/minimig/rel/minimig-rel2.zip), and then FreeWheel (http://aminet.net/package/util/mouse/FreeWheel.lha) , and I've tried different mice connected to the hub, but none seemed to work.

This is where the support was added in MiST
https://github.com/rkrajnc/minimig-mist/commit/d5b63745ceac6a4df0a3b1e5f7f64733ce9bf29c

**Comment by sorgelig** [comment]
MiSTer API doesn't support wheel yet.

**Comment by apolkosnik** [comment]
Thank you for the confirmation. Are there plans to add it or should I close the issue?

**Comment by sorgelig** [comment]
I have no plans currently as it's very minor issue and there are no cores actually need it (may be only ao486 with Win95). Even for Amiga the wheel is not a native feature and works not as good as in Windows. 
In the future i will add it when i will have nothing to do :)

**Comment by apolkosnik** [comment]
Thanks for making this work on the 7/1 release. Closing the issue.

**Comment by mickstone** [comment]
@apolkosnik I've been trying to get my mousewheel going in Minimig without much success. Can you describe how the minimigwheeldriver linked above is used?

**Comment by apolkosnik** [comment]
You don't need the Minimig driver. Freewheel from the aminet is sufficient. Just update both Minimig and the MiSTer main to the latest (in the scripts there's the updater that can do it for you if you have your MiSTer on the network.)

**Comment by mickstone** [comment]
Cheers. Yeah, running the latest versions via Retrodriven suite, but no mousewheel action with Freewheel loaded. Ah well, I'll poke around a bit more.

**Comment by apolkosnik** [comment]
Just use Freewheel from aminet alone, no need for the other driver

**Comment by limi** [comment]
I got it working. Contrary to what was stated here, you *do* need the “MinimigWheelDriver” to be running before launching FreeWheel. This can be found inside the Minimig release zip, e.g. https://meditation.somuch.guru/minimig/files/de1/rel/
