### ISSUE TITLE
Heavily garbled first screens in Final Odyssey

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/Minimig-AGA_MiSTer#68]
Greetings,

I've tried running Final Odyssey on an hard drive installation, and I have experienced heavily garbled graphics in the first two screens: the first one is a language selection screen, the second one is the title and loading screen.
They can easily be bypassed by simply pressing a joystick button and/or pressing the function key to load the corresponding save — the game itself seems to work as intended.
This is happening in direct video, both in OCS or AGA mode.
The screens display fine in emulation (although they seem to be using a weird semi-low definition mode, I can't seem to express it well, I joined a screenshot).

Cheers!

![Screen Shot](https://user-images.githubusercontent.com/62087454/83930704-2fae2c00-a799-11ea-82b3-a71ea06f9244.png)

**Comment by sorgelig** [comment]
to test it better i suggest to disable scandoubler, and don't use blank+. Also try both 68000 and 68020 modes.

**Comment by Left-Empty** [comment]
I tried all manners of settings for 20 minutes, and then noticed the unusual screen resolution displayed during switching by the MiSTer, and got struck by my stupidity: for some reason I had saved a default configuration that was switched to NTSC... Very embarassing. Please ignore me forever.

**Comment by sorgelig** [comment]
Shit happens :)
You can fill issues if you find them anyway.
