### ISSUE TITLE
cannot for the life of me set this up :( am i doing somethign wrong ?

### ISSUE THREAD

**Issue by dave11674** [MiSTer-devel/Minimig-AGA_MiSTer#69]
hi guys
i cannot for the life of me get this core running
ive setup to what i think is correct
kickstart.rom
hdd image
cpu
AGA mode
ram

i think im doing it all right
im running the latest software update as of yesterday. for the main system and core

[IMG_2848.zip](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer/files/4761886/IMG_2848.zip)

**Comment by rsn8887** [comment]
What is the error?

**Comment by sorgelig** [comment]
please go to forum: https://misterfpga.org/viewforum.php?f=4
Github is for completely other purpose.
