### ISSUE TITLE
Slowdown when intensive code is run (compared to real hardware)

### ISSUE THREAD

**Issue by famiclone6502** [MiSTer-devel/Minimig-AGA_MiSTer#72]
The demo [Parallax ZiF from Assembly 1995](http://www.pouet.net/prod.php?which=1149), has trouble with some of the sections where there is 3D graphics.

[This video](https://www.youtube.com/watch?v=qDZ4D63agTo) compares different configurations with the MiST. I know, it's not MiSTer, and it is out of date. The MiSTer's current firmware is running the demo closer to real hardware speed, but drops frames on the areas with intensive graphics.

There are other instances where intensive processing seems to slow down compared to the real thing, but this is just one reproducible example. 

Configuration: I used 68020, AGA, 2M chip, 384M fast, 0 slow, HRTmon disabled, PAL, and ran the demo's files off an HDF.

I also have a MiST but I haven't compared yet. I can submit a separate issue there if needed.

**Comment by sorgelig** [comment]
It's unclear to which hw you compare. It's much faster than standard A1200.
Do you compare with 060/50?

**Comment by famiclone6502** [comment]
I'm sorry, this was a bad example. I am closing until I can provide better information.

**Comment by sorgelig** [comment]
Current minimig version is intended to be not slower than stock A1200. Any extra performance is just a bonus. 
You cannot complain it's slower than expanded Amiga. It's not intended to compete with 040 or 060. Even 030 can be faster in some circumstances.

**Comment by famiclone6502** [comment]
Understood. Thank you for the clarification.
