### ISSUE TITLE
Rainbow Islands & Fire & Ice crashes in 68020 aga

### ISSUE THREAD

**Issue by ransom1122** [MiSTer-devel/Minimig-AGA_MiSTer#77]
Rainbow Islands & Fire & Ice games in whdload do not work is 68020 AGA mode..

I have the latest slaves...

Loading error reads

Error: Exception illegal instruction $ 10
at $ 7D7B6

I believe there may need to be a fix made for this as it seems.to be a timing issue.

**Comment by rsn8887** [comment]
I think this was fixed in latest release. At least I don't see this error anymore after updating today.

**Comment by limi** [comment]
Can confirm that this is fixed.
