### ISSUE TITLE
Allow VGA native modes to bypass scaler setting when using RTG output (feature request)

### ISSUE THREAD

**Issue by ChrisRaynor** [MiSTer-devel/Minimig-AGA_MiSTer#86]
RTG is currently only enabled for VGA out with the following INI setting:

vga_scaler=1  

For my setup with a CRT, I've found that the best possible output for PAL/NTSC games is when the scaler is disabled but I would still like to use RTG for my Workbench.

It would be helpful if RTG would only apply the vga_scaler setting when switching to a native screen mode (PAL/NTSC).   Then you could have vga_scaler=0 in the INI and still use RTG for the Workbench.

**Comment by sacredbanana** [comment]
This is exactly my most wanted feature. I like to keep the scaler off yet I don't want to have zero display if I don't have my HDMI monitor connected

**Comment by ChrisRaynor** [comment]
This has been delivered now and is working perfectly 👍
