### ISSUE TITLE
Is Ethernet supported on this core?

### ISSUE THREAD

**Issue by sardaukar** [MiSTer-devel/Minimig-AGA_MiSTer#9]
Will it every be? What kind of USB adapters work?

**Comment by sorgelig** [comment]
There is no Ethernet support in Minimig. You can only use UART TCP/IP connection in Minimig which will be transferred to Linux side and then Ethernet/Wifi will be used for internet connection.

**Comment by sardaukar** [comment]
Cool! Is this possible in the original MiST too?

**Comment by sorgelig** [comment]
MiST uses serial port pins (same as for MIDI), so you need to connect something like Raspberry Pi to have internet.

**Comment by sardaukar** [comment]
I have one of those :D is there a guide?

**Comment by sorgelig** [comment]
You need to ask on MiST forum. Or at least in MiST repository. It has no relation to MiSTer and i never tried it myself.

**Comment by sardaukar** [comment]
Thanks!
