### ISSUE TITLE
Feature Request: Zoomed Mode

### ISSUE THREAD

**Issue by limi** [MiSTer-devel/Minimig-AGA_MiSTer#90]
Just like with the C64 core, a majority of the Amiga games are built in a way that is a bit peculiar: They are using PAL (e.g. 256px height resolution), but leave the last 56px blank to make it possible to (theoretically) run the game in NTSC.

This causes a lot of empty space when running these games on a 16:9 display, and the C64 core has added an option in the OSD to have the display be “Zoomed”, which means that it cuts off the bottom part (in the Amiga case, the bottom 56px) to make it a 5× magnification instead of the 4× magnification that is the result when rendering Amiga PAL at 1080p.

The reason that you can’t just run these games in NTSC instead to get the 200px/5× magnification is that a lot of games were never properly tested in NTSC, as an example the game “Nitro” stutters on the night levels when run in NTSC mode, but works perfectly in PAL mode — but this leaves the bottom part of the screen blank.

Therefore, just like the C64 core, it would be nice to have this crop option (“Zoomed”) in the Amiga core as well, as the list of games that actually **need** the 256px height of PAL is very low, on the order of a few dozen games in the entire, vast Amiga games library.

**Comment by limi** [comment]
One way to do this would be to add the ability to switch between two different vadjust files. I currently have one vadjust file that does 4×, and one that does 5×, but I have to rename them on the file system to switch. Having a way to do this from the OSD (or, even better: via a command line tool on the Amiga side) would solve the problem.

(One suggestion: Optimally, the vadjust file could optionally support being located in the shared/ folder, then AmigaOS could update the file if MiSTer Main could see when it was updated and switch on game launch e.g. from WHDLoad scripts. This means any game could run in the optimal cropped mode and have the Amiga itself control what that is.)

**Comment by sorgelig** [comment]
I don't see any viable way to manage all these multiple zooms. 
Also Amiga has no fixed resolution like C64. Even visually the same resolution may have different video parameters from game to game making miss-match of adjusted zoom. So it will have a lot of video settings and on top of that many zoom options per each video setting.
No.. i don't like this mess. MiSTer is not a PC and has some limits in managing the settings making management done through hot-keys without visual feedback. 
I prefer to keep things simple and reasonable.

**Comment by Optiroc** [comment]
I submitted a [PR to Main_MiSTer](https://github.com/MiSTer-devel/Main_MiSTer/pull/309) that I believe provides a non-intrusive solution to this request.

It's quite simple: If the file "minimig_vadjust.dat" exists on the minimig shared folder, it will be loaded from there - and will consequtively be reloaded from that location on further video mode changes.

If the file doesn't exist, it will be loaded from /config as usual, once.

This opens up for is very simple Amiga side scripting to change the zoom/aspect ratio in for example WHDLoad launchers, without adding any UI or much complexity.

**Comment by limi** [comment]
This is great! 

I especially like this solution because it:

a) Doesn’t add any more UI complexity, 

b) Doesn’t affect anything unless you want to use it, 

c) Lets any Amiga launcher opt in and out of the 4×/5× zoom on a per-game basis, so the user just gets the correct one automatically without worrying about what the correct setting is.

**Comment by sorgelig** [comment]
yeah, should be a good idea to manage this setting from Amiga side.

**Comment by limi** [comment]
This was merged and released, so can be closed.
