### ISSUE TITLE
Time/Date not set

### ISSUE THREAD

**Issue by QuillOmega0** [MiSTer-devel/Minimig-AGA_MiSTer#97]
On set the time/date on the core is not being set correctly, it is set to the default date of the Workbench. I confirmed NTP is running, the menu and other cores do not have this issue

**Comment by sorgelig** [comment]
You cannot set time/date in the core. You have to set time on MiSTer. Actually it's set automatically over NTP. If you don't have RTC module, then after start/reset of MiSTer you have to wait for time to appear in Menu core and only then start the required core if you want to have correct time there.

**Comment by QuillOmega0** [comment]
That did it, just a lack of patience on my end. I have an RTC coming in anyway. Thank you and thank you for all your work on what I consider one of the greatest reasons to get a Mister
